### ISSUE TITLE
论文和代码不一致

### ISSUE THREAD

**Issue by l1n1999** [akira-l/mhem#1]
你好，我发现论文中CUB的函数为f (p) = Sgn((ap + b)^ϑ) + d，而在代码中这个全局偏置d好像并未体现，请问是为什么？

**Comment by akira-l** [comment]
Hi 感谢关注我的工作
这里的bias归在原始的ce_loss上算了，如果单独拎出来算也是一样的。
Line 103 @ train_model.py : mem_focal = mem_focal.mean()

**Comment by l1n1999** [comment]
好的，非常感谢
